application:
  search:
    config:
      maxOngoingSearches: 4
      taskDelayInSeconds: 1

spring:
  codec:
    max-in-memory-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always