application:
  search:
    config:
      maxOngoingSearches: 4
      taskDelayInSeconds: 1

spring:
  codec:
    max-in-memory-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: pricefinder.notifications@gmail.com
    password: mvirhbabeufcvydf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#logging:
#  level:
#    root: ERROR
#    com.gargoylesoftware.htmlunit: INFO
#    org.apache.http: INFO