application:
  search:
    config:
      maxOngoingSearches: 4
      taskDelayInSeconds: 1

spring:
  codec:
    max-in-memory-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: pricefinder.notifications@gmail.com
    password: M$PY49zCHr6Kr$&1sTMdwR2%
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true